=== mhowell-mozilla/mozilla-pipeline-schemas/schemas/messaging-system/snippets/snippets.1.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "properties": {
    "addon_version": {
      "type": "string"
    },
    "client_id": {
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$",
      "type": "string"
    },
    "event": {
      "description": "An event identifier",
      "type": "string"
    },
    "event_context": {
      "description": "A string that describes the context about this event",
      "type": "string"
    },
    "experiments": {
      "additionalProperties": {
        "properties": {
          "branch": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "description": "An object to record all active experiments, experiments IDs are stored as keys, and the value object stores the branch information. Example: {\"experiment_1\": {\"branch\": \"control\"}, \"experiment_2\": {\"branch\": \"treatment\"}}. This deprecates the \"shield_id\" used in activity-stream and messaging-system.",
      "type": "object"
    },
    "locale": {
      "type": "string"
    },
    "message_id": {
      "type": "string"
    },
    "profile_creation_date": {
      "type": "integer"
    },
    "release_channel": {
      "type": "string"
    },
    "shield_id": {
      "description": "[DEPRECATED]: use `experiments` instead. A semicolon separated string to store a list of Shield study IDs",
      "type": "string"
    },
    "version": {
      "type": "string"
    }
  },
  "required": [
    "client_id",
    "event",
    "message_id",
    "addon_version",
    "version",
    "locale"
  ],
  "title": "snippets",
  "type": "object"
}

=== mhowell-mozilla/mozilla-pipeline-schemas/validation/messaging-system/snippets.1.event.pass.json
{
  "client_id": "94642acb-4996-034b-916c-147da723cc41",
  "event": "IMPRESSION",
  "event_context": "n/a",
  "message_id": "TRAILHEAD_CARD_1",
  "locale": "en-US",
  "version": "71.0a1",
  "release_channel": "nightly",
  "addon_version": "20181206092619",
  "profile_creation_date": 17817,
  "experiments": {
    "exp_id_foo": {
      "branch": "control"
    },
    "exp_id_bar": {
      "branch": "treatment"
    }
  }
}

=== mhowell-mozilla/mozilla-pipeline-schemas/validation/messaging-system/onboarding.1.experiments.pass.json
{
  "client_id": "94642acb-4996-034b-916c-147da723cc41",
  "event": "IMPRESSION",
  "event_context": "n/a",
  "message_id": "12345",
  "locale": "en-US",
  "version": "71.0a1",
  "release_channel": "nightly",
  "addon_version": "20181206092619",
  "profile_creation_date": 17817,
  "experiments": {
    "exp_id_foo": {
      "branch": "control"
    },
    "exp_id_bar": {
      "branch": "treatment"
    }
  }
}
