=== mhowell-mozilla/mozilla-pipeline-schemas/schemas/telemetry/sync/sync.5.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "description": "Schema for v5 of sync pings added for GCP compatibility. This is a copy of v4 schema, as discussed in https://bugzilla.mozilla.org/show_bug.cgi?id=1572744#c3",
  "properties": {
    "application": {
      "$comment": "The application section is included here inline due to incompatible incoming data",
      "additionalProperties": false,
      "properties": {
        "architecture": {
          "type": "string"
        },
        "buildId": {
          "$comment": "Note that we drop the pattern requirement commonly used by other ping types for this field due to observed values in incoming data.",
          "type": "string"
        },
        "channel": {
          "type": "string"
        },
        "displayVersion": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "platformVersion": {
          "type": "string"
        },
        "vendor": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "xpcomAbi": {
          "type": "string"
        }
      },
      "required": [
        "architecture",
        "channel",
        "name",
        "platformVersion",
        "version"
      ],
      "type": "object"
    },
    "creationDate": {
      "$comment": "Note that we drop the pattern requirement commonly used by other ping types for this field due to observed values in incoming data.",
      "type": "string"
    },
    "id": {
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$",
      "type": "string"
    },
    "os": {
      "properties": {
        "locale": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "payload": {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description": "schema for Sync pings, documentation avaliable in toolkit/components/telemetry/docs/sync-ping.rst",
      "properties": {
        "deviceID": {
          "pattern": "^[0-9a-f]{64}$",
          "type": [
            "string",
            "null"
          ]
        },
        "devices": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "id": {
                "pattern": "^[0-9a-f]{64}$",
                "type": "string"
              },
              "os": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "syncID": {
                "type": "string"
              },
              "type": {
                "type": "string"
              },
              "version": {
                "type": [
                  "string",
                  "null"
                ]
              }
            },
            "type": "object"
          },
          "type": "array"
        },
        "discarded": {
          "minimum": 1,
          "type": "integer"
        },
        "events": {
          "items": {
            "items": [
              {
                "type": "integer"
              },
              {
                "type": "string"
              },
              {
                "type": "string"
              },
              {
                "type": "string"
              },
              {
                "type": [
                  "string",
                  "null"
                ]
              },
              {
                "additionalProperties": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "type": [
                  "object",
                  "null"
                ]
              }
            ],
            "maxItems": 6,
            "minItems": 4,
            "type": "array"
          },
          "type": "array"
        },
        "histograms": {
          "additionalProperties": {
            "anyOf": [
              {
                "$comment": "Desktop-style histograms",
                "additionalProperties": false,
                "properties": {
                  "bucket_count": {
                    "minimum": 0,
                    "type": "integer"
                  },
                  "histogram_type": {
                    "minimum": 0,
                    "type": "integer"
                  },
                  "log_sum": {
                    "minimum": 0,
                    "type": "number"
                  },
                  "log_sum_squares": {
                    "minimum": 0,
                    "type": "number"
                  },
                  "range": {
                    "items": {
                      "type": "integer"
                    },
                    "type": "array"
                  },
                  "sum": {
                    "minimum": 0,
                    "type": "integer"
                  },
                  "sum_squares_hi": {
                    "minimum": 0,
                    "type": "integer"
                  },
                  "sum_squares_lo": {
                    "minimum": 0,
                    "type": "integer"
                  },
                  "values": {
                    "additionalProperties": false,
                    "patternProperties": {
                      "^[0-9]+$": {
                        "minimum": 0,
                        "type": "integer"
                      }
                    },
                    "type": "object"
                  }
                },
                "type": "object"
              },
              {
                "$comment": "Nondesktop-style histograms",
                "additionalProperties": false,
                "properties": {
                  "counts": {
                    "items": {
                      "type": "integer"
                    },
                    "type": "array"
                  },
                  "histogram_type": {
                    "type": "integer"
                  },
                  "max": {
                    "type": "integer"
                  },
                  "min": {
                    "type": "integer"
                  },
                  "ranges": {
                    "items": {
                      "type": "integer"
                    },
                    "type": "array"
                  },
                  "sum": {
                    "type": "integer"
                  }
                },
                "type": "object"
              }
            ]
          },
          "type": "object"
        },
        "os": {
          "properties": {
            "locale": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "version": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "sessionStartDate": {
          "type": "string"
        },
        "syncNodeType": {
          "type": [
            "string",
            "null"
          ]
        },
        "syncs": {
          "items": {
            "properties": {
              "devices": {
                "items": {
                  "additionalProperties": false,
                  "properties": {
                    "id": {
                      "pattern": "^[0-9a-f]{64}$",
                      "type": "string"
                    },
                    "os": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "version": {
                      "type": [
                        "string",
                        "null"
                      ]
                    }
                  },
                  "type": "object"
                },
                "type": "array"
              },
              "didLogin": {
                "type": "boolean"
              },
              "engines": {
                "items": {
                  "properties": {
                    "failureReason": {
                      "properties": {
                        "code": {
                          "type": "integer"
                        },
                        "error": {
                          "type": "string"
                        },
                        "from": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name"
                      ],
                      "type": "object"
                    },
                    "incoming": {
                      "additionalProperties": false,
                      "anyOf": [
                        {
                          "required": [
                            "applied"
                          ]
                        },
                        {
                          "required": [
                            "failed"
                          ]
                        },
                        {
                          "required": [
                            "newFailed"
                          ]
                        },
                        {
                          "required": [
                            "reconciled"
                          ]
                        }
                      ],
                      "properties": {
                        "applied": {
                          "minimum": 0,
                          "type": "integer"
                        },
                        "failed": {
                          "minimum": 0,
                          "type": "integer"
                        },
                        "newFailed": {
                          "minimum": 0,
                          "type": "integer"
                        },
                        "reconciled": {
                          "minimum": 0,
                          "type": "integer"
                        },
                        "succeeded": {
                          "minimum": 0,
                          "type": "integer"
                        }
                      },
                      "type": "object"
                    },
                    "name": {
                      "type": "string"
                    },
                    "outgoing": {
                      "items": {
                        "additionalProperties": false,
                        "properties": {
                          "failed": {
                            "minimum": 1,
                            "type": "integer"
                          },
                          "sent": {
                            "minimum": 1,
                            "type": "integer"
                          }
                        },
                        "type": "object"
                      },
                      "minItems": 1,
                      "type": [
                        "array",
                        "object"
                      ]
                    },
                    "status": {
                      "type": "string"
                    },
                    "steps": {
                      "items": {
                        "additionalProperties": false,
                        "properties": {
                          "counts": {
                            "items": {
                              "properties": {
                                "count": {
                                  "type": "integer"
                                },
                                "name": {
                                  "type": "string"
                                }
                              },
                              "required": [
                                "name",
                                "count"
                              ],
                              "type": "object"
                            },
                            "minItems": 1,
                            "type": "array"
                          },
                          "name": {
                            "type": "string"
                          },
                          "took": {
                            "minimum": 0,
                            "type": "integer"
                          }
                        },
                        "required": [
                          "name"
                        ],
                        "type": "object"
                      },
                      "minItems": 1,
                      "type": "array"
                    },
                    "took": {
                      "minimum": -1,
                      "type": "integer"
                    },
                    "validation": {
                      "additionalProperties": false,
                      "properties": {
                        "checked": {
                          "minimum": 0,
                          "type": "integer"
                        },
                        "failureReason": {
                          "properties": {
                            "code": {
                              "type": "integer"
                            },
                            "error": {
                              "type": "string"
                            },
                            "from": {
                              "type": "string"
                            },
                            "name": {
                              "type": "string"
                            }
                          },
                          "required": [
                            "name"
                          ],
                          "type": "object"
                        },
                        "problems": {
                          "items": {
                            "properties": {
                              "count": {
                                "type": "integer"
                              },
                              "name": {
                                "type": "string"
                              }
                            },
                            "required": [
                              "name",
                              "count"
                            ],
                            "type": "object"
                          },
                          "minItems": 1,
                          "type": "array"
                        },
                        "took": {
                          "minimum": -1,
                          "type": "integer"
                        },
                        "version": {
                          "type": "integer"
                        }
                      },
                      "type": "object"
                    }
                  },
                  "required": [
                    "name"
                  ],
                  "type": "object"
                },
                "minItems": 0,
                "type": "array"
              },
              "failureReason": {
                "properties": {
                  "code": {
                    "type": "integer"
                  },
                  "error": {
                    "type": "string"
                  },
                  "from": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  }
                },
                "required": [
                  "name"
                ],
                "type": "object"
              },
              "status": {
                "additionalProperties": false,
                "anyOf": [
                  {
                    "required": [
                      "sync"
                    ]
                  },
                  {
                    "required": [
                      "service"
                    ]
                  }
                ],
                "properties": {
                  "service": {
                    "type": "string"
                  },
                  "sync": {
                    "type": "string"
                  }
                },
                "type": "object"
              },
              "took": {
                "minimum": -1,
                "type": "integer"
              },
              "when": {
                "type": "integer"
              },
              "why": {
                "type": "string"
              }
            },
            "type": "object"
          },
          "minItems": 0,
          "type": "array"
        },
        "uid": {
          "pattern": "^[0-9a-f]{32}$",
          "type": [
            "string",
            "null"
          ]
        },
        "version": {
          "minimum": 0,
          "type": "integer"
        },
        "why": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "type": {
      "enum": [
        "sync"
      ],
      "type": "string"
    },
    "version": {
      "maximum": 5,
      "minimum": 5,
      "type": "number"
    }
  },
  "required": [
    "application",
    "type",
    "id",
    "creationDate",
    "version",
    "payload"
  ],
  "title": "sync",
  "type": "object"
}

=== mhowell-mozilla/mozilla-pipeline-schemas/validation/telemetry/sync.4.null_device_version.pass.json
{
  "type": "sync",
  "id": "180bbc67-ed08-7846-a3d6-b82ada0b6f08",
  "creationDate": "2019-02-16T17:23:29.850Z",
  "version": 4,
  "application": {
    "architecture": "x86-64",
    "buildId": "20190213102848",
    "name": "Firefox",
    "version": "67.0a1",
    "displayVersion": "67.0a1",
    "vendor": "Mozilla",
    "platformVersion": "67.0a1",
    "xpcomAbi": "x86_64-gcc3",
    "channel": "nightly"
  },
  "payload": {
    "os": {
      "name": "Darwin",
      "version": "18.0.0",
      "locale": "en-CA"
    },
    "devices": [
      {
        "os": null,
        "version": null,
        "id": "f38b5add46460b49c7373bac4c99f96bfda39af90ed01ce2b4b24957cd5bbeba",
        "type": "mobile",
        "syncID": "e21b5add46460b49c7373bac4c99f96bfda39af90ed01ce2b4b24957cd5bbeba"
      }
    ],
    "why": "schedule",
    "version": 1,
    "syncs": [
      {
        "when": 1550298047806,
        "took": 2077,
        "why": "schedule",
        "engines": [
          {
            "name": "clients",
            "took": 277
          },
          {
            "name": "tabs",
            "took": 6
          },
          {
            "name": "bookmarks",
            "took": 16
          },
          {
            "name": "forms",
            "took": 4
          },
          {
            "name": "history",
            "took": 394,
            "outgoing": [
              {
                "sent": 8
              }
            ]
          }
        ]
      },
      {
        "when": 1550301657882,
        "took": 2058,
        "devices": [
          {
            "os": "Android",
            "version": "65.0.1",
            "id": "f38b5add46460b49c7373bac4c99f96bfda39af90ed01ce2b4b24957cd5bbeba"
          },
          {
            "os": null,
            "version": null,
            "id": "a38b5add46460b49c7373bac4c99f96bfda39af90ed01ce2b4b24957cd5bbebf"
          }
        ],
        "why": "schedule",
        "engines": [
          {
            "name": "clients",
            "took": 624
          },
          {
            "name": "tabs",
            "took": 3
          },
          {
            "name": "bookmarks",
            "took": 12,
            "steps": [
              {
                "name": "fetchLocalTree",
                "took": 123,
                "counts": [
                  {
                    "name": "items",
                    "count": 1000
                  },
                  {
                    "name": "deletions",
                    "count": 10
                  }
                ]
              },
              {
                "name": "fetchRemoteTree",
                "took": 456
              }
            ]
          },
          {
            "name": "forms",
            "took": 5
          },
          {
            "name": "history",
            "took": 413,
            "outgoing": [
              {
                "sent": 8
              }
            ]
          }
        ]
      }
    ],
    "uid": "43720380d3e0935ca8d715b98d0da438",
    "deviceID": "0dd0695bf3753be0bf3de5f9809b145f68441b65bfeac85d89b31e04718bbaa6",
    "sessionStartDate": "2019-02-15T13:00:00.0-04:00",
    "syncNodeType": "some-type",
    "histograms": {
      "PWMGR_NUM_SAVED_PASSWORDS": {
        "min": 0,
        "max": 100,
        "histogram_type": 0,
        "sum": 5,
        "ranges": [1, 50, 100],
        "counts": [0, 1, 0]
      },
      "PWMGR_BLOCKLIST_NUM_SITES": {
        "min": 0,
        "max": 750,
        "histogram_type": 0,
        "sum": 208,
        "ranges": [175, 196, 219],
        "counts": [0, 1, 0]
      }
    },
    "events": [
      [145994282,"sync","run","maintenance","bookmarks"],
      [162808985,"sync","run","maintenance","bookmarks"],
      [165025232,"sync","open","mirror","success",{"size":"352","serverTime":"1566174585.14"}]
    ]
  }
}
