=== mhowell-mozilla/mozilla-pipeline-schemas/schemas/activity-stream/sessions/sessions.1.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "properties": {
    "addon_version": {
      "type": "string"
    },
    "client_id": {
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$",
      "type": "string"
    },
    "experiments": {
      "additionalProperties": {
        "properties": {
          "branch": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "description": "An object to record all active experiments, experiments IDs are stored as keys, and the value object stores the branch information. Example: {\"experiment_1\": {\"branch\": \"control\"}, \"experiment_2\": {\"branch\": \"treatment\"}}. This deprecates the \"shield_id\" used in activity-stream and messaging-system.",
      "type": "object"
    },
    "locale": {
      "type": "string"
    },
    "page": {
      "enum": [
        "about:newtab",
        "about:home",
        "about:welcome",
        "unknown",
        "n/a",
        "both",
        "https://newtab.firefoxchina.cn/newtab/as/activity-stream.html"
      ],
      "type": "string"
    },
    "perf": {
      "properties": {
        "highlights_data_late_by_ms": {
          "description": "Latency of the data availability for Highlights",
          "type": "integer"
        },
        "is_preloaded": {
          "description": "Whether or not this session is preloaded",
          "type": "boolean"
        },
        "load_trigger_ts": {
          "description": "To store the timestamp (ms since Unix epoch) when this session gets triggered",
          "type": "integer"
        },
        "load_trigger_type": {
          "enum": [
            "menu_plus_or_keyboard",
            "unexpected",
            "first_window_opened"
          ],
          "type": "string"
        },
        "topsites_data_late_by_ms": {
          "description": "Latency of the data availability for Top Sites",
          "type": "integer"
        },
        "topsites_first_painted_ts": {
          "description": "To store the timestamp (ms since Unix epoch) when the Top Sites is first painted",
          "type": "integer"
        },
        "topsites_icon_stats": {
          "description": "Icon stats for Top Sites, only sent if Top Sites is enabled",
          "properties": {
            "custom_screenshot": {
              "type": "integer"
            },
            "no_image": {
              "type": "integer"
            },
            "rich_icon": {
              "type": "integer"
            },
            "screenshot": {
              "type": "integer"
            },
            "screenshot_with_icon": {
              "type": "integer"
            },
            "tippytop": {
              "type": "integer"
            }
          },
          "type": "object"
        },
        "topsites_pinned": {
          "description": "The total number of pinned Top Sites in this session",
          "type": "integer"
        },
        "topsites_search_shortcuts": {
          "description": "The total number of search shortcuts in this session",
          "type": "integer"
        },
        "visibility_event_rcvd_ts": {
          "description": "To store the timestamp (ms since Unix epoch) when the page is made visible to the user in this session",
          "type": "integer"
        }
      },
      "required": [
        "load_trigger_type"
      ],
      "type": "object"
    },
    "profile_creation_date": {
      "description": "Profile age in days since Unix epoch",
      "type": "integer"
    },
    "release_channel": {
      "type": "string"
    },
    "session_duration": {
      "description": "The duration of this session in milliseconds. The session begins at `perf.visibility_event_rcvd_ts` and ends when the page is navigated away",
      "type": "integer"
    },
    "session_id": {
      "description": "A UUID representing an Activity Stream session. This can be used to do table joins between `sessions` and `events` in Activity Stream. Note that `n/a` denotes that the session is not applicable in the context.",
      "pattern": "^\\{[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\\}$|^n/a$",
      "type": "string"
    },
    "shield_id": {
      "description": "[DEPRECATED]: use `experiments` instead. A semicolon separated string to store a list of Shield study IDs",
      "type": "string"
    },
    "user_prefs": {
      "description": "An encoded integer representing user's preferences of Activity Stream",
      "type": "integer"
    },
    "version": {
      "type": "string"
    }
  },
  "required": [
    "client_id",
    "addon_version",
    "page",
    "version",
    "locale",
    "session_id",
    "session_duration",
    "perf",
    "user_prefs",
    "profile_creation_date"
  ],
  "title": "sessions",
  "type": "object"
}

=== mhowell-mozilla/mozilla-pipeline-schemas/validation/activity-stream/sessions.1.sample.pass.json
{
  "locale": "en-US",
  "client_id": "4dd69e99-07e7-c040-a514-ccde0cfd4881",
  "version": "72.0a1",
  "release_channel": "nightly",
  "addon_version": "20191119043902",
  "user_prefs": 255,
  "session_id": "{3e3fce7a-d015-7d44-9404-3547a600a9ec}",
  "page": "about:home",
  "profile_creation_date": 16587,
  "session_duration": 7000,
  "perf": {
    "load_trigger_type": "first_window_opened",
    "is_preloaded": false,
    "load_trigger_ts": 1578946833472,
    "visibility_event_rcvd_ts": 1578946834265,
    "topsites_icon_stats": {
      "custom_screenshot": 0,
      "screenshot_with_icon": 0,
      "screenshot": 0,
      "tippytop": 6,
      "rich_icon": 0,
      "no_image": 0
    },
    "topsites_pinned": 0,
    "topsites_search_shortcuts": 1,
    "topsites_data_late_by_ms": 197,
    "highlights_data_late_by_ms": 241,
    "topsites_first_painted_ts": 1578946834726
  },
  "experiments": {
    "exp_id_foo": {
      "branch": "control"
    },
    "exp_id_bar": {
      "branch": "treatment"
    }
  }
}
