=== mhowell-mozilla/mozilla-pipeline-schemas/schemas/activity-stream/events/events.1.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "properties": {
    "action_position": {
      "description": "A zero based integer indicating the position of this event",
      "type": "integer"
    },
    "addon_version": {
      "type": "string"
    },
    "browser_session_id": {
      "description": "A mirror of the browser sessionId, as defined in https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/master/schemas/telemetry/main/main.4.schema.json",
      "type": "string"
    },
    "client_id": {
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$",
      "type": "string"
    },
    "event": {
      "description": "An event identifier",
      "type": "string"
    },
    "experiments": {
      "additionalProperties": {
        "properties": {
          "branch": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "description": "An object to record all active experiments, experiments IDs are stored as keys, and the value object stores the branch information. Example: {\"experiment_1\": {\"branch\": \"control\"}, \"experiment_2\": {\"branch\": \"treatment\"}}. This deprecates the \"shield_id\" used in activity-stream and messaging-system.",
      "type": "object"
    },
    "locale": {
      "type": "string"
    },
    "page": {
      "enum": [
        "about:newtab",
        "about:home",
        "about:welcome",
        "unknown",
        "n/a",
        "both",
        "https://newtab.firefoxchina.cn/newtab/as/activity-stream.html"
      ],
      "type": "string"
    },
    "profile_creation_date": {
      "type": "integer"
    },
    "region": {
      "type": "string"
    },
    "release_channel": {
      "type": "string"
    },
    "session_id": {
      "description": "A UUID representing an Activity Stream session. This can be used to do table joins between `sessions` and `events` in Activity Stream. Note that `n/a` denotes that the session is not applicable in the context.",
      "pattern": "^\\{[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\\}$|^n/a$",
      "type": "string"
    },
    "shield_id": {
      "description": "[DEPRECATED]: use `experiments` instead. A semicolon separated string to store a list of Shield study IDs",
      "type": "string"
    },
    "source": {
      "type": "string"
    },
    "user_prefs": {
      "description": "An encoded integer representing user's preferences of Activity Stream",
      "type": "integer"
    },
    "value": {
      "description": "A string that describes the context about this event",
      "type": "string"
    },
    "version": {
      "type": "string"
    }
  },
  "required": [
    "client_id",
    "event",
    "addon_version",
    "version",
    "locale"
  ],
  "title": "events",
  "type": "object"
}

=== mhowell-mozilla/mozilla-pipeline-schemas/validation/activity-stream/events.1.browser_session_id.pass.json
{
  "locale": "en-US",
  "client_id": "4dd69e99-07e7-c040-a514-ccde0cfd4881",
  "version": "72.0a1",
  "release_channel": "nightly",
  "addon_version": "20191119043902",
  "user_prefs": 255,
  "session_id": "{3e3fce7a-d015-7d44-9404-3547a600a9ec}",
  "page": "about:newtab",
  "event": "CLICK",
  "source": "TOP_SITES",
  "action_position": 0,
  "value": "{\"icon_type\": \"rich_icon\"}",
  "profile_creation_date": 16587,
  "region": "CA",
  "shield_id": "activity-stream-shield-study-bug-1238122",
  "browser_session_id": "e7e52665-7db3-f348-9918-e93160eb2ef3"
}

=== mhowell-mozilla/mozilla-pipeline-schemas/validation/activity-stream/events.1.experiments.pass.json
{
  "locale": "en-US",
  "client_id": "4dd69e99-07e7-c040-a514-ccde0cfd4881",
  "version": "72.0a1",
  "release_channel": "nightly",
  "addon_version": "20191119043902",
  "user_prefs": 255,
  "session_id": "{3e3fce7a-d015-7d44-9404-3547a600a9ec}",
  "page": "about:newtab",
  "event": "CLICK",
  "source": "TOP_SITES",
  "action_position": 0,
  "value": "{\"icon_type\": \"rich_icon\"}",
  "profile_creation_date": 16587,
  "region": "CA",
  "experiments": {
    "exp_id_foo": {
      "branch": "control"
    },
    "exp_id_bar": {
      "branch": "treatment"
    }
  }
}
