=== mhowell-mozilla/mozilla-pipeline-schemas/schemas/telemetry/deletion-request/deletion-request.4.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "properties": {
    "application": {
      "additionalProperties": false,
      "properties": {
        "architecture": {
          "type": "string"
        },
        "buildId": {
          "pattern": "^[0-9]{10}",
          "type": "string"
        },
        "channel": {
          "type": "string"
        },
        "displayVersion": {
          "pattern": "^[0-9]{2,3}\\.",
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "platformVersion": {
          "pattern": "^[0-9]{2,3}\\.",
          "type": "string"
        },
        "vendor": {
          "type": "string"
        },
        "version": {
          "pattern": "^[0-9]{2,3}\\.",
          "type": "string"
        },
        "xpcomAbi": {
          "type": "string"
        }
      },
      "required": [
        "architecture",
        "buildId",
        "channel",
        "name",
        "platformVersion",
        "version",
        "vendor",
        "xpcomAbi"
      ],
      "type": "object"
    },
    "clientId": {
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$",
      "type": "string"
    },
    "creationDate": {
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
      "type": "string"
    },
    "id": {
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$",
      "type": "string"
    },
    "payload": {
      "additionalProperties": false,
      "properties": {
        "scalars": {
          "properties": {
            "content": {
              "additionalProperties": {
                "type": [
                  "integer",
                  "string",
                  "boolean"
                ]
              },
              "type": "object"
            },
            "parent": {
              "additionalProperties": {
                "type": [
                  "integer",
                  "string",
                  "boolean"
                ]
              },
              "type": "object"
            }
          },
          "type": "object"
        }
      },
      "type": "object"
    },
    "type": {
      "enum": [
        "deletion-request"
      ],
      "type": "string"
    },
    "version": {
      "maximum": 4,
      "minimum": 4,
      "type": "number"
    }
  },
  "required": [
    "application",
    "clientId",
    "creationDate",
    "id",
    "type",
    "version"
  ],
  "title": "deletion-request",
  "type": "object"
}

=== mhowell-mozilla/mozilla-pipeline-schemas/validation/telemetry/deletion-request.4.payload.pass.json
{
  "type": "deletion-request",
  "id": "d7754449-8cb1-4df6-b07b-c60dab6f5d66",
  "creationDate": "2018-07-09T14:13:14.497Z",
  "version": 4,
  "application": {
    "architecture": "x86-64",
    "buildId": "20180709105613",
    "name": "Firefox",
    "version": "63.0a1",
    "displayVersion": "63.0a1",
    "vendor": "Mozilla",
    "platformVersion": "63.0a1",
    "xpcomAbi": "x86_64-gcc3",
    "channel": "default"
  },
  "clientId": "c4582ba1-79fc-1f47-ae2a-671118dccd8b",
  "payload": {
    "scalars": {
      "parent": {
        "browser.engagement.unfiltered_uri_count": 782
      }
    }
  }
}
